"""
Django settings for rrhh project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&2r20tt5*7+)w(g&y*ls81!=6#0o_ox+ynsp7gy223m5nz@^2t'

# SECURITY WARNING: don't run with debug turned on in production!
# para el dezpliegue cambie el debug a false para que no aparescan el tipo de error y demas
DEBUG = True

# agregar entre comillas el valor del dominio
ALLOWED_HOSTS = ['code2c.com/demo','www.code2c.com','code2c.com','46.202.149.244']


# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'panel',
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.locale.LocaleMiddleware', 
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'panel.middleware.PorcentajeMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rrhh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rrhh.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


# puede configurar a una base de datos Mysql
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/La_Paz'

USE_I18N = True
USE_TZ = False

import os

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static/')]


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGOUT_REDIRECT_URL = '/'

LOGIN_URL = '/session/'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com' 
EMAIL_PORT = 587  
EMAIL_USE_TLS = True 
# EMAIL_HOST_USER = 'nuevavidaparajuan@gmail.com'  
# EMAIL_HOST_PASSWORD = 'lfcq luah ejlu irix' 

EMAIL_HOST_USER = 'sistemas@agencia-vilaseca.com'  
EMAIL_HOST_PASSWORD = 'wses bhgq pexk xosh' 

DEFAULT_FROM_EMAIL = 'sistemas@agencia-vilaseca.com'  
GOOGLE_MAPS_API_KEY = 'AIzaSyCh7gKB66uvFfsnrQ-R66wFxGVNE2JL6H4' 
# GOOGLE_MAPS_API_KEY = 'AIzaSyAT0pvaRjOJwxwXYccivd8JP2xq5GULEMw'

 
FERNET_KEY = b'NkylMZgXlRqtSGBnE6dZEdJBRCNMfiPY0t-k2KgJNOI='

APPEND_SLASH = False

#para EL QR DE EQUIPOS agregar url dominio
BASE_URL_QR = "https://c1fb-200-105-158-39.ngrok-free.app"

#para control de usuarios envio de informes
BASE_CORREO = 'programacionvilaseca@gmail.com'


# validar dominios agregar la url del 
CSRF_TRUSTED_ORIGINS = [
    'https://c1fb-200-105-158-39.ngrok-free.app',
    
     
]

DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760 