# Generated by Django 4.2 on 2024-11-19 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id_certificado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField(null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificado', models.DateTimeField(auto_now_add=True, null=True)),
                ('correo', models.CharField(max_length=100)),
                ('dirigido', models.CharField(max_length=50)),
                ('emitido', models.CharField(max_length=50, null=True)),
                ('tipo', models.CharField(max_length=20, null=True)),
                ('estado', models.IntegerField(null=True)),
                ('activo', models.BooleanField(default=True)),
                ('gestion', models.IntegerField(null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitudes',
            },
        ),
        migrations.CreateModel(
            name='EstadoCertificado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('gestion', models.IntegerField(null=True)),
                ('correlativo', models.IntegerField(null=True)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('observacion', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.certificados')),
                ('usuario_modificado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'estado_certificado',
            },
        ),
        migrations.CreateModel(
            name='CertificadoAprobados',
            fields=[
                ('id_certificado_a', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=100)),
                ('dirigido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100, null=True)),
                ('emitido', models.CharField(max_length=50, null=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, null=True)),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('tipo', models.CharField(max_length=20, null=True)),
                ('estado', models.IntegerField(null=True)),
                ('gestion', models.IntegerField(null=True)),
                ('correlativo', models.IntegerField(null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cierre', models.BooleanField(default=True)),
                ('solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.certificados')),
                ('usuario_modificado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certificados',
            },
        ),
    ]
