# Generated by Django 4.2 on 2024-11-20 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='ClasificacionAnti',
            fields=[
                ('id_antiguedad', models.AutoField(primary_key=True, serialize=False)),
                ('antiguedad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'clasificacion_anti',
            },
        ),
        migrations.CreateModel(
            name='ClasificacionGrupo',
            fields=[
                ('id_clas', models.AutoField(primary_key=True, serialize=False)),
                ('clasificacion', models.CharField(max_length=15)),
                ('rango_inicio', models.IntegerField()),
                ('rango_fin', models.IntegerField()),
            ],
            options={
                'db_table': 'clasificacion_grupo',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_depa', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'estado_civil',
            },
        ),
        migrations.CreateModel(
            name='Generacion',
            fields=[
                ('id_generacion', models.AutoField(primary_key=True, serialize=False)),
                ('generacion', models.CharField(max_length=15)),
                ('rango_inicio', models.IntegerField()),
                ('rango_fin', models.IntegerField()),
            ],
            options={
                'db_table': 'generacion',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'genero',
            },
        ),
        migrations.CreateModel(
            name='Sangre',
            fields=[
                ('id_sangre', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'sangre',
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('contrato', models.CharField(max_length=35)),
                ('descripcion', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'tipo_contrato',
            },
        ),
        migrations.CreateModel(
            name='TipoRegistro',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('registro', models.CharField(max_length=35)),
                ('descripcion', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'tipo_registro',
            },
        ),
        migrations.CreateModel(
            name='Empleo',
            fields=[
                ('id_empleo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_trabajador', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField()),
                ('nombre_trab', models.CharField(max_length=100, null=True)),
                ('numero_trabajo', models.IntegerField(null=True)),
                ('nro_interno', models.IntegerField(null=True)),
                ('correo_corp', models.CharField(max_length=20)),
                ('antiguo', models.BooleanField()),
                ('inicio_contrato', models.DateField()),
                ('modalidad', models.CharField(max_length=20)),
                ('clasificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.clasificacionanti')),
                ('empleado_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.tipocontrato')),
                ('tipo_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.tiporegistro')),
            ],
            options={
                'db_table': 'empleo',
            },
        ),
        migrations.CreateModel(
            name='DatosPersonal',
            fields=[
                ('id_datos', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.IntegerField(null=True)),
                ('expedido', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=30)),
                ('ap_paterno', models.CharField(max_length=30)),
                ('ap_materno', models.CharField(max_length=30, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.CharField(max_length=100)),
                ('alergias', models.CharField(max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('clasificacion_grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.clasificaciongrupo')),
                ('empleado_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estado_civil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.estadocivil')),
                ('generacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.generacion')),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.genero')),
                ('tipo_sangre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.sangre')),
            ],
            options={
                'db_table': 'datos_personal',
            },
        ),
        migrations.CreateModel(
            name='ContactosPersonal',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('celular', models.IntegerField(null=True)),
                ('whatsapp', models.IntegerField(null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('latitud', models.FloatField(null=True)),
                ('longitud', models.FloatField(null=True)),
                ('contacto1_nombre', models.CharField(max_length=50)),
                ('contacto1_parentesco', models.CharField(max_length=50)),
                ('contacto1_numero', models.IntegerField(null=True)),
                ('contacto2_nombre', models.CharField(max_length=50)),
                ('contacto2_parentesco', models.CharField(max_length=50)),
                ('contacto2_numero', models.IntegerField()),
                ('hijos', models.BooleanField()),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.ciudad')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.departamento')),
                ('empleado_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contacto_personal',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.departamento'),
        ),
    ]
