# Generated by Django 4.2 on 2024-11-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_ciudad_clasificacionanti_clasificaciongrupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='expedido',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
