# Generated by Django 4.2 on 2024-12-04 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0006_remove_estadocivil_fecha_modificacion_ciudad_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carnet',
            fields=[
                ('id_carnet', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.FileField(blank=True, null=True, upload_to='carnet/')),
                ('fecha_registro', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'carnet',
            },
        ),
        migrations.CreateModel(
            name='CartaPresentacion',
            fields=[
                ('id_carta_presentacion', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.FileField(blank=True, null=True, upload_to='carta_presentacion/')),
                ('fecha_registro', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'carta_presentacion',
            },
        ),
        migrations.CreateModel(
            name='CertificadoExterno',
            fields=[
                ('id_certificado_externo', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.FileField(blank=True, null=True, upload_to='certificado_externo/')),
                ('fecha_registro', models.DateField()),
                ('entidad', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('tiempo', models.IntegerField()),
            ],
            options={
                'db_table': 'certificado_externo',
            },
        ),
        migrations.CreateModel(
            name='ClasificacionFile',
            fields=[
                ('id_code_file', models.AutoField(primary_key=True, serialize=False)),
                ('modalidad', models.CharField(max_length=30)),
                ('siglas', models.CharField(max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'clasificacion_file',
            },
        ),
        migrations.CreateModel(
            name='ConveniosContratos',
            fields=[
                ('id_convenios_contratos', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.FileField(blank=True, null=True, upload_to='convenios_contratos/')),
                ('fecha_registro', models.DateField()),
                ('fecha_emision', models.DateField()),
                ('entidad', models.CharField(max_length=20)),
                ('tiempo', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('clasificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.clasificacionfile')),
            ],
            options={
                'db_table': 'convenios_contratos',
            },
        ),
        migrations.CreateModel(
            name='Croquis',
            fields=[
                ('id_croquis', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.FileField(blank=True, null=True, upload_to='croquis/')),
                ('fecha_registro', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('clasificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.clasificacionfile')),
            ],
            options={
                'db_table': 'croquis',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id_curriculum', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.FileField(blank=True, null=True, upload_to='curriculum/')),
                ('fecha_registro', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('clasificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.clasificacionfile')),
            ],
            options={
                'db_table': 'curriculum',
            },
        ),
        migrations.CreateModel(
            name='Felcc',
            fields=[
                ('id_felcc', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.FileField(blank=True, null=True, upload_to='felcc/')),
                ('fecha_registro', models.DateField()),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('clasificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.clasificacionfile')),
            ],
            options={
                'db_table': 'felcc',
            },
        ),
        migrations.CreateModel(
            name='Felcn',
            fields=[
                ('id_felcn', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.FileField(blank=True, null=True, upload_to='felcn/')),
                ('fecha_registro', models.DateField()),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('clasificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.clasificacionfile')),
            ],
            options={
                'db_table': 'felcn',
            },
        ),
        migrations.CreateModel(
            name='Varios',
            fields=[
                ('id_varios', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.FileField(blank=True, null=True, upload_to='varios/')),
                ('fecha_registro', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('clasificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.clasificacionfile')),
            ],
            options={
                'db_table': 'varios',
            },
        ),
        migrations.CreateModel(
            name='Rejab',
            fields=[
                ('id_rejab', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.FileField(blank=True, null=True, upload_to='rejab/')),
                ('fecha_registro', models.DateField()),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('clasificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.clasificacionfile')),
            ],
            options={
                'db_table': 'rejab',
            },
        ),
        migrations.CreateModel(
            name='PautasActuacion',
            fields=[
                ('id_pautas', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.FileField(blank=True, null=True, upload_to='pautas/')),
                ('fecha_registro', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('clasificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.clasificacionfile')),
            ],
            options={
                'db_table': 'pautas',
            },
        ),
        migrations.CreateModel(
            name='Memorandum',
            fields=[
                ('id_memorandum', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.FileField(blank=True, null=True, upload_to='memorandum/')),
                ('fecha_registro', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('clasificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.clasificacionfile')),
            ],
            options={
                'db_table': 'memorandum',
            },
        ),
        migrations.CreateModel(
            name='LuzAgua',
            fields=[
                ('id_factura_luz', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.FileField(blank=True, null=True, upload_to='factura_luz/')),
                ('fecha_registro', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('clasificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.clasificacionfile')),
            ],
            options={
                'db_table': 'factura_luz',
            },
        ),
        migrations.CreateModel(
            name='Induccion',
            fields=[
                ('id_induccion', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.FileField(blank=True, null=True, upload_to='induccion/')),
                ('fecha_registro', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('clasificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.clasificacionfile')),
            ],
            options={
                'db_table': 'induccion',
            },
        ),
        migrations.CreateModel(
            name='HojaVida',
            fields=[
                ('id_hoja', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.FileField(blank=True, null=True, upload_to='hoja_vida/')),
                ('fecha_registro', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('clasificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.clasificacionfile')),
            ],
            options={
                'db_table': 'hoja_vida',
            },
        ),
        migrations.CreateModel(
            name='FilePersonal',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False)),
                ('carnet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.carnet')),
                ('carta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.cartapresentacion')),
                ('certificado_externo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.certificadoexterno')),
                ('contratos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.convenioscontratos')),
                ('croquis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.croquis')),
                ('curriculum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.curriculum')),
                ('empleado_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.luzagua')),
                ('felcc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.felcc')),
                ('felcn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.felcn')),
                ('hoja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.hojavida')),
                ('induccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.induccion')),
                ('memo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.memorandum')),
                ('pautas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.pautasactuacion')),
                ('rejab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.rejab')),
                ('varios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.varios')),
            ],
            options={
                'db_table': 'file_personal',
            },
        ),
        migrations.AddField(
            model_name='certificadoexterno',
            name='clasificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.clasificacionfile'),
        ),
        migrations.CreateModel(
            name='CertificadoAcademico',
            fields=[
                ('id_certificado_academico', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.FileField(blank=True, null=True, upload_to='certificado_academico/')),
                ('fecha_registro', models.DateField()),
                ('fecha_egreso', models.DateField()),
                ('titulo', models.CharField(max_length=20)),
                ('tiempo', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('clasificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.clasificacionfile')),
            ],
            options={
                'db_table': 'certificado_academico',
            },
        ),
        migrations.AddField(
            model_name='cartapresentacion',
            name='clasificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.clasificacionfile'),
        ),
        migrations.AddField(
            model_name='carnet',
            name='clasificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.clasificacionfile'),
        ),
    ]
