# Generated by Django 4.2 on 2024-12-04 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_carnet_cartapresentacion_certificadoexterno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepersonal',
            name='empleado_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.datospersonal'),
        ),
    ]
