# Generated by Django 4.2 on 2024-12-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_alter_filepersonal_empleado_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepersonal',
            name='carnet',
        ),
        migrations.RemoveField(
            model_name='filepersonal',
            name='carta',
        ),
        migrations.RemoveField(
            model_name='filepersonal',
            name='certificado_externo',
        ),
        migrations.RemoveField(
            model_name='filepersonal',
            name='contratos',
        ),
        migrations.RemoveField(
            model_name='filepersonal',
            name='croquis',
        ),
        migrations.RemoveField(
            model_name='filepersonal',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='filepersonal',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='filepersonal',
            name='felcc',
        ),
        migrations.RemoveField(
            model_name='filepersonal',
            name='felcn',
        ),
        migrations.RemoveField(
            model_name='filepersonal',
            name='hoja',
        ),
        migrations.RemoveField(
            model_name='filepersonal',
            name='induccion',
        ),
        migrations.RemoveField(
            model_name='filepersonal',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='filepersonal',
            name='pautas',
        ),
        migrations.RemoveField(
            model_name='filepersonal',
            name='rejab',
        ),
        migrations.RemoveField(
            model_name='filepersonal',
            name='varios',
        ),
    ]
