# Generated by Django 4.2 on 2024-12-05 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_remove_filepersonal_carnet_remove_filepersonal_carta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnet',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.filepersonal'),
        ),
        migrations.AddField(
            model_name='cartapresentacion',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.filepersonal'),
        ),
        migrations.AddField(
            model_name='certificadoacademico',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.filepersonal'),
        ),
        migrations.AddField(
            model_name='certificadoexterno',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.filepersonal'),
        ),
        migrations.AddField(
            model_name='convenioscontratos',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.filepersonal'),
        ),
        migrations.AddField(
            model_name='croquis',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.filepersonal'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.filepersonal'),
        ),
        migrations.AddField(
            model_name='felcc',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.filepersonal'),
        ),
        migrations.AddField(
            model_name='felcn',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.filepersonal'),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.filepersonal'),
        ),
        migrations.AddField(
            model_name='induccion',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.filepersonal'),
        ),
        migrations.AddField(
            model_name='luzagua',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.filepersonal'),
        ),
        migrations.AddField(
            model_name='memorandum',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.filepersonal'),
        ),
        migrations.AddField(
            model_name='pautasactuacion',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.filepersonal'),
        ),
        migrations.AddField(
            model_name='rejab',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.filepersonal'),
        ),
        migrations.AddField(
            model_name='varios',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.filepersonal'),
        ),
    ]
