# Generated by Django 4.2 on 2024-12-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_alter_clasificacionfile_siglas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenioscontratos',
            name='fecha_emision',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='felcc',
            name='fecha_emision',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='felcc',
            name='fecha_vencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='felcn',
            name='fecha_emision',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='felcn',
            name='fecha_vencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rejab',
            name='fecha_emision',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rejab',
            name='fecha_vencimiento',
            field=models.DateField(null=True),
        ),
    ]
