# Generated by Django 4.2 on 2024-12-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_alter_certificadoexterno_entidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoacademico',
            name='fecha_egreso',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='certificadoacademico',
            name='tiempo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='certificadoacademico',
            name='titulo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
