# Generated by Django 4.2 on 2024-12-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_alter_certificadoacademico_fecha_egreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenioscontratos',
            name='entidad',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='convenioscontratos',
            name='tiempo',
            field=models.IntegerField(null=True),
        ),
    ]
