# Generated by Django 4.2 on 2024-12-10 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_alter_carnet_ruta_alter_cartapresentacion_ruta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoaprobados',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.filepersonal'),
        ),
    ]
