# Generated by Django 4.2 on 2024-12-13 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('panel', '0019_modulo_permiso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='grupo',
        ),
        migrations.AddField(
            model_name='modulo',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
