# Generated by Django 4.2 on 2024-12-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_remove_permiso_grupo_modulo_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
