# Generated by Django 4.2 on 2024-12-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0022_permiso_agregar'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoaprobados',
            name='id_dirigido',
            field=models.IntegerField(null=True),
        ),
    ]
