# Generated by Django 4.2.17 on 2024-12-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0023_certificadoaprobados_id_dirigido'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificados',
            name='id_dirigido',
            field=models.IntegerField(null=True),
        ),
    ]
