# Generated by Django 4.2 on 2024-12-20 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0025_alter_contactospersonal_contacto1_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.FileField(blank=True, null=True, upload_to='')),
                ('fecha_registro', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('clasificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.clasificacionfile')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.filepersonal')),
            ],
            options={
                'db_table': 'foto',
            },
        ),
    ]
