# Generated by Django 4.2 on 2024-12-20 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0027_remove_datospersonal_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactospersonal',
            name='whatsapp',
        ),
    ]
