# Generated by Django 4.2 on 2024-12-20 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0028_remove_contactospersonal_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonal',
            name='clasificacion_grupo',
        ),
        migrations.RemoveField(
            model_name='datospersonal',
            name='generacion',
        ),
    ]
