# Generated by Django 4.2 on 2024-12-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0029_remove_datospersonal_clasificacion_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificados',
            name='requerimiento',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
