# Generated by Django 4.2 on 2024-12-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0030_certificados_requerimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactospersonal',
            name='foto_puerta',
            field=models.ImageField(blank=True, null=True, upload_to='puertas/'),
        ),
    ]
