# Generated by Django 4.2 on 2024-12-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0031_contactospersonal_foto_puerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleo',
            name='whatsapp',
            field=models.IntegerField(null=True),
        ),
    ]
