# Generated by Django 4.2 on 2024-12-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0032_empleo_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificacionanti',
            name='rango_fin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clasificacionanti',
            name='rango_inicio',
            field=models.IntegerField(null=True),
        ),
    ]
