# Generated by Django 4.2 on 2025-01-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0034_empleo_centro_trabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo', models.IntegerField(null=True)),
                ('tamano', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('antiguo', models.BooleanField(default=False)),
                ('qr', models.ImageField(blank=True, null=True, upload_to='qr_equipo/')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'equipos_oficina',
            },
        ),
    ]
