# Generated by Django 4.2 on 2025-01-06 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0035_equipos'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='fecha_registro',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=50)),
                ('fecha_asignado', models.DateField(null=True)),
                ('fecha_devuelto', models.DateField(null=True)),
                ('estado', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.equipos')),
            ],
            options={
                'db_table': 'asignacion_equipos',
            },
        ),
    ]
