# Generated by Django 4.2 on 2025-01-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0036_equipos_fecha_registro_asignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='tipo',
            field=models.CharField(max_length=30),
        ),
    ]
