# Generated by Django 4.2 on 2025-01-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0038_equipos_foto_equipos_imagen_1_equipos_imagen_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='auxiliares',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
