# Generated by Django 4.2 on 2025-01-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0039_equipos_auxiliares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='equipo',
        ),
    ]
