# Generated by Django 4.2 on 2025-01-07 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0040_remove_asignacion_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.asignacion'),
        ),
    ]
