# Generated by Django 4.2 on 2025-01-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0041_equipos_asignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='equipo',
            field=models.IntegerField(null=True),
        ),
    ]
