# Generated by Django 4.2 on 2025-01-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0042_asignacion_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='imagen_5',
            field=models.ImageField(blank=True, null=True, upload_to='equipos/'),
        ),
    ]
