# Generated by Django 4.2 on 2025-01-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0043_equipos_imagen_5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos',
            name='foto',
        ),
    ]
