# Generated by Django 4.2 on 2025-01-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0044_remove_equipos_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='equipos',
            name='asignacion',
        ),
    ]
