# Generated by Django 4.2 on 2025-01-09 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0045_remove_equipos_activo_remove_equipos_asignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipos',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.asignacion'),
        ),
    ]
