# Generated by Django 4.2 on 2025-01-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0046_equipos_activo_equipos_asignacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos',
            name='auxiliares',
        ),
    ]
