# Generated by Django 4.2 on 2025-01-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0047_remove_equipos_auxiliares'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='auxiliares',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
