# Generated by Django 4.2 on 2025-01-09 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0048_equipos_auxiliares'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipos',
            old_name='imagen_5',
            new_name='imagen_6',
        ),
    ]
