# Generated by Django 4.2 on 2025-01-09 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0049_rename_imagen_5_equipos_imagen_6'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipos',
            old_name='imagen_6',
            new_name='imagen_0',
        ),
    ]
