# Generated by Django 4.2 on 2025-01-09 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0052_equipos_fecha_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambiosEquipos',
            fields=[
                ('id_cambios', models.AutoField(primary_key=True, serialize=False)),
                ('equipo', models.IntegerField(null=True)),
                ('fecha', models.DateTimeField(null=True)),
                ('descripcion', models.CharField(max_length=150, null=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cambios_equipos',
            },
        ),
    ]
