# Generated by Django 4.2 on 2025-01-09 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0053_cambiosequipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionEquipo',
            fields=[
                ('id_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(null=True)),
                ('lapzo', models.CharField(max_length=50, null=True)),
                ('observaciones', models.CharField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'devolucion_equipos',
            },
        ),
        migrations.AddField(
            model_name='equipos',
            name='devolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.devolucionequipo'),
        ),
    ]
