# Generated by Django 4.2 on 2025-01-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0054_devolucionequipo_equipos_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='equipo',
            field=models.CharField(max_length=50),
        ),
    ]
