# Generated by Django 4.2 on 2025-01-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0056_equipos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='estado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
