# Generated by Django 4.2 on 2025-01-09 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0057_alter_equipos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucionequipo',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devolucionequipo',
            name='equipo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
