# Generated by Django 4.2 on 2025-01-13 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0060_usuariocorreos_adjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='devolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.devolucionequipo'),
        ),
    ]
