# Generated by Django 4.2 on 2025-01-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0062_controlusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocorreos',
            name='asunto',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
