# Generated by Django 4.2 on 2025-01-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0063_usuariocorreos_asunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocorreos',
            name='asunto',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
