# Generated by Django 4.2 on 2025-01-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0064_alter_usuariocorreos_asunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlusuario',
            name='clave',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='controlusuario',
            name='tipo',
            field=models.IntegerField(null=True),
        ),
    ]
