# Generated by Django 4.2 on 2025-01-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0066_rename_clave_controlusuario_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificacionCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('tiempo_expiracion', models.DateTimeField()),
            ],
        ),
    ]
