# Generated by Django 4.2 on 2025-01-16 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0068_controlusuario_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocorreos',
            name='compartido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuariocorreos',
            name='estado',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='AsignacionCorreosUsuarios',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('observacion', models.CharField(max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('correo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.usuariocorreos')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asignar_correo_usuario',
            },
        ),
    ]
