# Generated by Django 4.2 on 2025-01-16 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0069_usuariocorreos_compartido_usuariocorreos_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocorreos',
            name='correo_alt',
        ),
        migrations.AddField(
            model_name='asignacioncorreosusuarios',
            name='correo_alt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='BajaCorreosUsuarios',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('observacion', models.CharField(max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('correo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.usuariocorreos')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'baja_correo_usuario',
            },
        ),
    ]
