# Generated by Django 4.2 on 2025-01-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0070_remove_usuariocorreos_correo_alt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocorreos',
            name='descripcion',
        ),
    ]
