# Generated by Django 4.2 on 2025-01-16 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0071_remove_usuariocorreos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacioncorreosusuarios',
            name='baja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.bajacorreosusuarios'),
        ),
    ]
