# Generated by Django 4.2 on 2025-01-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0072_asignacioncorreosusuarios_baja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocorreos',
            name='empleado',
        ),
        migrations.AddField(
            model_name='usuariocorreos',
            name='correo_alt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
