# Generated by Django 4.2 on 2025-01-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0073_remove_usuariocorreos_empleado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacioncorreosusuarios',
            name='correo',
        ),
    ]
