# Generated by Django 4.2 on 2025-01-21 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0076_bajacorreosusuarios_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignadoEquipoCuenta',
            fields=[
                ('id_cuenta_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_equipo', models.CharField(max_length=20, null=True)),
                ('fecha_cambio', models.DateField(null=True)),
                ('clave', models.CharField(max_length=100, null=True)),
                ('estado', models.IntegerField(null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asignar_cuenta_eq',
            },
        ),
        migrations.CreateModel(
            name='EquiposCuentas',
            fields=[
                ('id_cuenta_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('datos', models.CharField(max_length=100, null=True)),
                ('tipo', models.CharField(max_length=30, null=True)),
                ('asignado_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.asignadoequipocuenta')),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.equipos')),
            ],
            options={
                'db_table': 'equipo_cuentas',
            },
        ),
    ]
