# Generated by Django 4.2 on 2025-01-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0077_asignadoequipocuenta_equiposcuentas'),
    ]

    operations = [
        migrations.AddField(
            model_name='equiposcuentas',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
