# Generated by Django 4.2 on 2025-01-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0078_equiposcuentas_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContrasenaEquipos',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_equipo_contrasena',
            },
        ),
    ]
