# Generated by Django 4.2 on 2025-01-23 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0079_tipocontrasenaequipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equiposcuentas',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.tipocontrasenaequipos'),
        ),
    ]
