# Generated by Django 4.2 on 2025-01-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0080_alter_equiposcuentas_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equiposcuentas',
            name='usuario_cuenta',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
