# Generated by Django 4.2 on 2025-01-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0081_equiposcuentas_usuario_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='equiposcuentas',
            name='observaciones',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
