# Generated by Django 4.2 on 2025-01-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0084_equiposcuentas_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojavida',
            name='drive',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
