# Generated by Django 4.2 on 2025-01-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0085_hojavida_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnet',
            name='drive',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cartapresentacion',
            name='drive',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificadoacademico',
            name='drive',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificadoexterno',
            name='drive',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='convenioscontratos',
            name='drive',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='croquis',
            name='drive',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='drive',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='felcc',
            name='drive',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='felcn',
            name='drive',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='foto',
            name='drive',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='induccion',
            name='drive',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='luzagua',
            name='drive',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='memorandum',
            name='drive',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pautasactuacion',
            name='drive',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rejab',
            name='drive',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='varios',
            name='drive',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
