# Generated by Django 4.2 on 2025-01-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0086_carnet_drive_cartapresentacion_drive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificados',
            name='drive',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
