# Generated by Django 4.2 on 2025-01-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0087_certificados_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoaprobados',
            name='drive',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
