# Generated by Django 4.2 on 2025-01-27 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0088_certificadoaprobados_drive'),
    ]

    operations = [
        migrations.CreateModel(
            name='auditoriaEquipos',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(null=True)),
                ('detalle', models.CharField(max_length=200, null=True)),
                ('drive', models.CharField(max_length=200, null=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.equipos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria_equipos',
            },
        ),
    ]
