# Generated by Django 4.2 on 2025-01-27 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0089_auditoriaequipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudServicioTecnico',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(null=True)),
                ('mensaje', models.CharField(max_length=200, null=True)),
                ('diagnostico', models.CharField(max_length=200, null=True)),
                ('accion', models.CharField(max_length=200, null=True)),
                ('correccion', models.CharField(max_length=200, null=True)),
                ('recomendacion', models.CharField(max_length=200, null=True)),
                ('estado_final', models.CharField(max_length=200, null=True)),
                ('observacion', models.CharField(max_length=200, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'soporte_tecnico',
            },
        ),
    ]
