# Generated by Django 4.2 on 2025-01-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0090_solicitudserviciotecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudserviciotecnico',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudserviciotecnico',
            name='fecha_respuesta',
            field=models.DateTimeField(null=True),
        ),
    ]
