# Generated by Django 4.2 on 2025-01-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0091_solicitudserviciotecnico_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudserviciotecnico',
            name='foto',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
