# Generated by Django 4.2 on 2025-01-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0092_solicitudserviciotecnico_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudserviciotecnico',
            name='foto',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudserviciotecnico',
            name='mensaje',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
