# Generated by Django 4.2 on 2025-01-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0093_alter_solicitudserviciotecnico_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacioncorreosusuarios',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
