# Generated by Django 4.2 on 2025-01-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0094_asignacioncorreosusuarios_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudserviciotecnico',
            name='codigo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
