# Generated by Django 4.2 on 2025-01-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0095_solicitudserviciotecnico_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleo',
            name='antiguo',
            field=models.BooleanField(null=True),
        ),
    ]
