# Generated by Django 4.2 on 2025-01-28 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0096_alter_empleo_antiguo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactospersonal',
            name='empleado_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.datospersonal'),
        ),
    ]
