# Generated by Django 4.2 on 2025-01-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0101_alter_empleo_empleado_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactospersonal',
            name='mapa',
            field=models.BooleanField(default=False),
        ),
    ]
