# Generated by Django 4.2 on 2025-01-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0102_contactospersonal_mapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonal',
            name='completo',
            field=models.BooleanField(default=False),
        ),
    ]
