# Generated by Django 4.2 on 2025-01-29 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0103_datospersonal_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleo',
            name='correo_corp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.asignacioncorreosusuarios'),
        ),
    ]
