# Generated by Django 4.2 on 2025-01-30 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0104_alter_empleo_correo_corp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignarCuentasSoftwares',
            fields=[
                ('id_asignado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(null=True)),
                ('usuario', models.CharField(max_length=50, null=True)),
                ('observacion', models.CharField(max_length=250, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'asig_cuentas_software',
            },
        ),
        migrations.CreateModel(
            name='Softwares',
            fields=[
                ('id_sistema', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(null=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('enlace', models.CharField(max_length=200, null=True)),
                ('puerto', models.IntegerField(null=True)),
                ('ip', models.CharField(max_length=25, null=True)),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sistemas_informaticos',
            },
        ),
        migrations.CreateModel(
            name='CuentasSoftwares',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(null=True)),
                ('usuario', models.CharField(max_length=50, null=True)),
                ('tipo_usuario', models.CharField(max_length=20, null=True)),
                ('contra', models.CharField(max_length=200, null=True)),
                ('estado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.asignarcuentassoftwares')),
            ],
            options={
                'db_table': 'cuentas_software',
            },
        ),
        migrations.CreateModel(
            name='BajaCuentasSoftwares',
            fields=[
                ('id_asignado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(null=True)),
                ('usuario', models.CharField(max_length=50, null=True)),
                ('observacion', models.CharField(max_length=250, null=True)),
                ('usuario_baja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'baja_cuentas_software',
            },
        ),
        migrations.AddField(
            model_name='asignarcuentassoftwares',
            name='baja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.bajacuentassoftwares'),
        ),
        migrations.AddField(
            model_name='asignarcuentassoftwares',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
