# Generated by Django 4.2 on 2025-01-30 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0105_asignarcuentassoftwares_softwares_cuentassoftwares_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentassoftwares',
            name='sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.softwares'),
        ),
    ]
