# Generated by Django 4.2 on 2025-01-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0106_cuentassoftwares_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentassoftwares',
            name='observaciones',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
