# Generated by Django 4.2 on 2025-01-31 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0107_cuentassoftwares_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='BajaCuentaTeletrabajo',
            fields=[
                ('id_baja', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(null=True)),
                ('observaciones', models.CharField(max_length=200, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'baja_cuenta_teletrabajo',
            },
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id_oficina', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(null=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('direccion', models.CharField(max_length=200, null=True)),
                ('latitud', models.FloatField(null=True)),
                ('longitud', models.FloatField(null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'oficinas',
            },
        ),
        migrations.CreateModel(
            name='CuentasTeletrabajo',
            fields=[
                ('id_teletrabajo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(null=True)),
                ('ip_equipo', models.CharField(max_length=20, null=True)),
                ('tipo_acceso', models.CharField(max_length=50, null=True)),
                ('firmware', models.CharField(max_length=20, null=True)),
                ('dst', models.CharField(max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.CharField(max_length=200, null=True)),
                ('baja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.bajacuentateletrabajo')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.equipos')),
            ],
            options={
                'db_table': 'cuenta_teletrabajo',
            },
        ),
    ]
