# Generated by Django 4.2 on 2025-01-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0108_bajacuentateletrabajo_oficina_cuentasteletrabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentasteletrabajo',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
