# Generated by Django 4.2 on 2025-01-31 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0109_cuentasteletrabajo_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentasteletrabajo',
            name='baja',
        ),
        migrations.RemoveField(
            model_name='cuentasteletrabajo',
            name='empleado',
        ),
        migrations.CreateModel(
            name='AsignarCuentaTeletrabajo',
            fields=[
                ('id_asignado', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.CharField(max_length=200, null=True)),
                ('fecha', models.DateTimeField(null=True)),
                ('baja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.bajacuentateletrabajo')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asignar_cuenta_teletrabajo',
            },
        ),
    ]
