# Generated by Django 4.2 on 2025-02-03 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0112_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoBackups',
            fields=[
                ('id_estado_b', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(null=True)),
                ('periodo', models.CharField(max_length=20, null=True)),
                ('estado', models.IntegerField(null=True)),
                ('activo', models.BooleanField(default=True)),
                ('informe_drive', models.CharField(max_length=200, null=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.equipos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'estado_backup',
            },
        ),
    ]
