# Generated by Django 4.2 on 2025-02-03 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0113_estadobackups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backups',
            fields=[
                ('id_backup', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(null=True)),
                ('periodo', models.CharField(max_length=20, null=True)),
                ('regional', models.CharField(max_length=20, null=True)),
                ('estado', models.IntegerField(null=True)),
                ('activo', models.BooleanField(default=True)),
                ('informe_drive', models.CharField(max_length=200, null=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.equipos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backup',
            },
        ),
        migrations.CreateModel(
            name='AreasOficina',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(null=True)),
                ('area', models.DateTimeField(null=True)),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.oficina')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'area_oficina',
            },
        ),
    ]
