# Generated by Django 4.2 on 2025-02-03 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0114_backups_areasoficina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backups',
            name='informe_drive',
        ),
        migrations.AddField(
            model_name='backups',
            name='gestion',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='VerificacionBackups',
            fields=[
                ('id_backup', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(null=True)),
                ('gestion', models.IntegerField(null=True)),
                ('disco_duro', models.CharField(max_length=20, null=True)),
                ('regional', models.CharField(max_length=20, null=True)),
                ('obs', models.CharField(max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.equipos')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verificar_backup',
            },
        ),
        migrations.AddField(
            model_name='backups',
            name='verificar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.verificacionbackups'),
        ),
    ]
