# Generated by Django 4.2 on 2025-02-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0115_remove_backups_informe_drive_backups_gestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificacionbackups',
            name='activo',
        ),
    ]
