# Generated by Django 4.2 on 2025-02-03 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0116_remove_verificacionbackups_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backups',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.estadobackups'),
        ),
    ]
