# Generated by Django 4.2 on 2025-02-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0117_alter_backups_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='backups',
            name='observaciones',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
