# Generated by Django 4.2 on 2025-02-04 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0118_backups_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignarcuentateletrabajo',
            name='dst',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asignarcuentateletrabajo',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.equipos'),
        ),
        migrations.AddField(
            model_name='asignarcuentateletrabajo',
            name='firmware',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asignarcuentateletrabajo',
            name='ip_equipo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asignarcuentateletrabajo',
            name='tipo_acceso',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
