# Generated by Django 4.2 on 2025-02-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0119_asignarcuentateletrabajo_dst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacionbackups',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='verificacionbackups',
            name='fechar_verificacion',
            field=models.DateTimeField(null=True),
        ),
    ]
