# Generated by Django 4.2 on 2025-02-05 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0120_verificacionbackups_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoBackups',
            fields=[
                ('id_disco', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(null=True)),
                ('activo', models.BooleanField(default=True)),
                ('numero', models.CharField(max_length=200, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'disco_backup',
            },
        ),
        migrations.AlterField(
            model_name='verificacionbackups',
            name='disco_duro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.discobackups'),
        ),
    ]
