# Generated by Django 4.2 on 2025-02-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0121_discobackups_alter_verificacionbackups_disco_duro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificacionbackups',
            old_name='responsable',
            new_name='revisor_cambio',
        ),
    ]
