# Generated by Django 4.2 on 2025-02-12 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0123_backups_tipo_backup'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupsCorreos',
            fields=[
                ('id_backup_correos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(null=True)),
                ('regional', models.CharField(max_length=20, null=True)),
                ('disco_duro', models.CharField(max_length=200, null=True)),
                ('tipo_correo', models.CharField(max_length=50, null=True)),
                ('desde', models.DateField(null=True)),
                ('hasta', models.DateField(null=True)),
                ('motivo', models.CharField(max_length=50, null=True)),
                ('solicitante', models.CharField(max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.CharField(max_length=200, null=True)),
                ('correo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.equipos')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.estadobackups')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backup_correo',
            },
        ),
    ]
