# Generated by Django 4.2 on 2025-02-12 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0126_backupscorreos_ubicacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoBackupsCorreos',
            fields=[
                ('id_estado_b', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(null=True)),
                ('regional', models.CharField(max_length=20, null=True)),
                ('total', models.IntegerField(null=True)),
                ('usado', models.IntegerField(null=True)),
                ('restante', models.IntegerField(null=True)),
                ('activo', models.BooleanField(default=True)),
                ('correo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.usuariocorreos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'estado_backup_correo',
            },
        ),
    ]
