# Generated by Django 4.2 on 2025-02-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0128_alter_backupscorreos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadobackupscorreos',
            name='estado',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
