# Generated by Django 4.2 on 2025-02-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0130_calendario'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='color',
            field=models.CharField(default='#e01ab5', max_length=7),
        ),
    ]
