# Generated by Django 4.2 on 2025-02-14 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0131_calendario_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='area',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='calendario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='color',
            field=models.CharField(default='#00aae4', max_length=7),
        ),
    ]
