# Generated by Django 4.2 on 2025-02-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0133_mantenimientos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimientos',
            name='correo',
        ),
    ]
