# Generated by Django 4.2 on 2025-02-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0134_remove_mantenimientos_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimientos',
            name='tipo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
