# Generated by Django 4.2 on 2025-02-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0135_mantenimientos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientos',
            name='estado',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
