# Generated by Django 4.2 on 2025-02-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0137_mantenimientos_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimientos',
            name='diagnostico',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mantenimientos',
            name='solucion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
