# Generated by Django 4.2 on 2025-02-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0138_mantenimientos_diagnostico_mantenimientos_solucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupscorreos',
            name='fecha_ejecucion',
            field=models.DateTimeField(null=True),
        ),
    ]
