# Generated by Django 4.2 on 2025-02-17 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0139_backupscorreos_fecha_ejecucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSistemas',
            fields=[
                ('id_b_sistema', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_planificada', models.DateTimeField(null=True)),
                ('fecha_realizada', models.DateTimeField(null=True)),
                ('fecha_verificada', models.DateTimeField(null=True)),
                ('gestion', models.IntegerField(null=True)),
                ('disco_duro', models.CharField(max_length=250, null=True)),
                ('observaciones', models.CharField(max_length=250, null=True)),
                ('oficina', models.CharField(max_length=50, null=True)),
                ('area', models.CharField(max_length=250, null=True)),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.softwares')),
            ],
            options={
                'db_table': 'backup_sistema',
            },
        ),
    ]
