# Generated by Django 4.2 on 2025-02-17 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0140_backupsistemas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupsistemas',
            name='disco_duro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.discobackups'),
        ),
    ]
