# Generated by Django 4.2 on 2025-02-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0141_alter_backupsistemas_disco_duro'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupsistemas',
            name='periodo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
