# Generated by Django 4.2 on 2025-02-18 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0142_backupsistemas_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(null=True)),
                ('area', models.CharField(max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='AreasCargos',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(null=True)),
                ('cargo', models.CharField(max_length=50, null=True)),
                ('planillado', models.CharField(max_length=50, null=True)),
                ('subpersonal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.areas')),
            ],
            options={
                'db_table': 'areas_cargos',
            },
        ),
    ]
