# Generated by Django 4.2 on 2025-02-19 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0143_areas_areascargos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleo',
            name='clasificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.areascargos'),
        ),
    ]
