# Generated by Django 4.2 on 2025-02-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0144_alter_empleo_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonal',
            name='complemento',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
