# Generated by Django 4.2 on 2025-02-24 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0145_datospersonal_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.departamento'),
        ),
    ]
