# Generated by Django 4.2 on 2025-02-26 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0147_alter_empleo_centro_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupsistemas',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.areas'),
        ),
    ]
