# Generated by Django 4.2 on 2025-02-26 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0148_alter_backupsistemas_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupsistemas',
            name='oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.oficina'),
        ),
    ]
