# Generated by Django 4.2 on 2025-03-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0149_alter_backupsistemas_oficina'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupsistemas',
            name='disco_verificado',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
