# Generated by Django 4.2 on 2025-03-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0150_backupsistemas_disco_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calendario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
