# Generated by Django 5.1.7 on 2025-03-12 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0152_alter_calendario_activo_alter_calendario_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backupsistemas',
            name='ubicacion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_planificada', models.DateTimeField(null=True)),
                ('fecha_realizada', models.DateTimeField(null=True)),
                ('fecha_verificada', models.DateTimeField(null=True)),
                ('observaciones', models.CharField(max_length=250, null=True)),
                ('detalle', models.CharField(max_length=100, null=True)),
                ('precio', models.FloatField(null=True)),
                ('factura', models.CharField(max_length=200, null=True)),
                ('cotizacion', models.CharField(max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.oficina')),
            ],
            options={
                'db_table': 'gastos',
            },
        ),
    ]
